trigger: none # only run in PRs which are handled by branch policies

variables:
  - template: 'templates/variables.yml'

pool:
  vmImage: $(vmImageName)

steps:
  - template: 'templates/build-docker.yml'
